/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.soinsoftware.accountability.view;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import co.com.soinsoftware.accountability.controller.LicenseController;

/**
 *
 * @author Carlos Rodriguez
 * @since 08/09/2016
 * @version 1.0
 */
public class JFLicense extends JFrame {

	private static final long serialVersionUID = -7412203075150596935L;

	private static final String MSG_INVALID_LICENSE_REQUIRED = "Introduzca una licencia válida";

	private static final String MSG_LICENSE_REQUIRED = "Introduzca la licencia";

	private final LicenseController controller;

	public JFLicense() {
		this.controller = new LicenseController();
		this.initComponents();
		final Dimension screenSize = Toolkit.getDefaultToolkit()
				.getScreenSize();
		this.setResizable(false);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setLocation((int) (screenSize.getWidth() / 2 - 200),
				(int) (screenSize.getHeight() / 2 - 200));
	}

	private boolean validateLicense() {
		boolean isValid = true;
		final String license = this.jtfLicense.getText();
		// final String encLicense =
		// this.controller.encryptLicenseData(license);
		if (license.equals("")) {
			isValid = false;
			ViewUtils.showMessage(this, MSG_LICENSE_REQUIRED,
					ViewUtils.TITLE_REQUIRED_FIELDS, JOptionPane.ERROR_MESSAGE);
		} else if (!this.controller.isValidLicense(license)) {
			isValid = false;
			ViewUtils.showMessage(this, MSG_INVALID_LICENSE_REQUIRED,
					ViewUtils.TITLE_REQUIRED_FIELDS, JOptionPane.ERROR_MESSAGE);
		}
		return isValid;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lbImage = new javax.swing.JLabel();
		jlbDeveloped = new javax.swing.JLabel();
		jlbLicense = new javax.swing.JLabel();
		jbtRegister = new javax.swing.JButton();
		jtfLicense = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("CPMIPYMES");
		setIconImage(Toolkit.getDefaultToolkit().getImage(
				getClass().getResource("/images/accountability.png")));

		lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/soin.png"))); // NOI18N

		jlbDeveloped.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
		jlbDeveloped.setText("Introduzca la licencia.");

		jlbLicense.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
		jlbLicense.setText("Licencia:");

		jbtRegister.setBackground(new java.awt.Color(16, 135, 221));
		jbtRegister.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
		jbtRegister.setForeground(new java.awt.Color(255, 255, 255));
		jbtRegister.setText("Registrar");
		jbtRegister.setPreferredSize(new java.awt.Dimension(89, 23));
		jbtRegister.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtRegisterActionPerformed(evt);
			}
		});

		jtfLicense.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		lbImage,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		388,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addComponent(
																										jlbDeveloped,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										364,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(35,
																										35,
																										35)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jbtRegister,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jlbLicense)
																																.addGap(271,
																																		271,
																																		271))
																												.addComponent(
																														jtfLicense,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														320,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addComponent(jlbDeveloped)
								.addGap(45, 45, 45)
								.addComponent(jlbLicense)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jtfLicense,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(11, 11, 11)
								.addComponent(jbtRegister,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										58, Short.MAX_VALUE)
								.addComponent(lbImage,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										35,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jbtRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtRegisterActionPerformed
		if (this.validateLicense()) {
			final String license = this.jtfLicense.getText();
			this.controller.saveLicense(license);
			final JFLogin login = new JFLogin();
			login.setVisible(true);
			this.setVisible(false);
		}
	}// GEN-LAST:event_jbtRegisterActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbtRegister;
	private javax.swing.JLabel jlbDeveloped;
	private javax.swing.JLabel jlbLicense;
	private javax.swing.JTextField jtfLicense;
	private javax.swing.JLabel lbImage;
	// End of variables declaration//GEN-END:variables
}
